name: tech
favicon: null
layout_spectrum: 1
typography_spectrum: 0.88785
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#5b2e19'
    - '#93827b'
    - '#c8d8cd'
    - '#d84d19'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose:
  - name: engagement
    item: null
    url: null
