layout_spectrum: 0.33163
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose:
  - name: engagement
    url: null
    item: null
color:
  saturation: 0.5
  brandStrength: 1
  lightness: 0.5
  brandColors:
    - '#060604'
    - '#9A7F6E'
    - '#FBFFFF'
    - '#E0CEB5'
    - '#0293B3'
  rhythmicContrast: 0.5
typography_spectrum: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: tech
